name: music_metadata
description: Dart library to edit music metadata.
version: 1.0.0
repository: https://github.com/hghgthifg/music_metadata

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

license:
  name: MIT License
  url: https://opensource.org/licenses/MIT
